-- Fix broken French accents in countries data.
-- Run this file in the Supabase SQL Editor.
-- This script updates existing rows only and does not change schema.

update countries
set name = case code
  when 'DZ' then 'Algérie'
  when 'AM' then 'Arménie'
  when 'BA' then 'Bosnie-Herzégovine'
  when 'BJ' then 'Bénin'
  when 'BR' then 'Brésil'
  when 'EC' then 'Équateur'
  when 'CK' then 'Îles Cook'
  when 'MH' then 'Îles Marshall'
  when 'ET' then 'Éthiopie'
  when 'GE' then 'Géorgie'
  when 'GN' then 'Guinée'
  when 'HT' then 'Haïti'
  when 'ID' then 'Indonésie'
  when 'KR' then 'Corée du Sud'
  when 'CI' then 'Côte d’Ivoire'
  when 'CR' then 'Costa Rica'
  when 'CD' then 'République démocratique du Congo'
  when 'CG' then 'République du Congo'
  when 'DO' then 'République dominicaine'
  when 'ST' then 'São Tomé-et-Príncipe'
  when 'TL' then 'Timor oriental'
  when 'TR' then 'Turquie'
  when 'AE' then 'Émirats arabes unis'
  else name
end
where code in (
  'DZ',
  'AM',
  'BA',
  'BJ',
  'BR',
  'EC',
  'CK',
  'MH',
  'ET',
  'GE',
  'GN',
  'HT',
  'ID',
  'KR',
  'CI',
  'CR',
  'CD',
  'CG',
  'DO',
  'ST',
  'TL',
  'TR',
  'AE'
);

update countries
set region = case
  when code in (
    'CK',
    'FJ',
    'FM',
    'KI',
    'MH',
    'NR',
    'NU',
    'PW',
    'SB',
    'TO',
    'TV',
    'VU',
    'WS'
  ) then 'Océanie'
  when code in (
    'AG',
    'BB',
    'BS',
    'CU',
    'DM',
    'DO',
    'GD',
    'HT',
    'JM',
    'KN',
    'LC',
    'TT',
    'VC'
  ) then 'Caraïbes'
  when code in (
    'AR',
    'BO',
    'BR',
    'CL',
    'CO',
    'EC',
    'GY',
    'PE',
    'PY',
    'SR',
    'UY',
    'VE'
  ) then 'Amérique du Sud'
  when code in (
    'BI',
    'DJ',
    'ER',
    'ET',
    'KE',
    'KM',
    'MG',
    'MU',
    'MW',
    'MZ',
    'RW',
    'SC',
    'SO',
    'TZ',
    'UG',
    'ZM',
    'ZW'
  ) then 'Afrique de l’Est'
  when code in (
    'CN',
    'HK',
    'JP',
    'KR',
    'MO',
    'MN',
    'TW'
  ) then 'Asie de l’Est'
  when code in (
    'BJ',
    'BF',
    'CI',
    'CV',
    'GH',
    'GM',
    'GN',
    'GW',
    'LR',
    'ML',
    'MR',
    'NE',
    'NG',
    'SN',
    'SL',
    'TG'
  ) then 'Afrique de l’Ouest'
  else region
end
where code in (
  'CK',
  'FJ',
  'FM',
  'KI',
  'MH',
  'NR',
  'NU',
  'PW',
  'SB',
  'TO',
  'TV',
  'VU',
  'WS',
  'AG',
  'BB',
  'BS',
  'CU',
  'DM',
  'DO',
  'GD',
  'HT',
  'JM',
  'KN',
  'LC',
  'TT',
  'VC',
  'AR',
  'BO',
  'BR',
  'CL',
  'CO',
  'EC',
  'GY',
  'PE',
  'PY',
  'SR',
  'UY',
  'VE',
  'CN',
  'HK',
  'JP',
  'KR',
  'MO',
  'MN',
  'TW',
  'BI',
  'DJ',
  'ER',
  'ET',
  'KE',
  'KM',
  'MG',
  'MU',
  'MW',
  'MZ',
  'RW',
  'SC',
  'SO',
  'TZ',
  'UG',
  'ZM',
  'ZW',
  'BJ',
  'BF',
  'CI',
  'CV',
  'GH',
  'GM',
  'GN',
  'GW',
  'LR',
  'ML',
  'MR',
  'NE',
  'NG',
  'SN',
  'SL',
  'TG'
);

update countries
set notes = case
  when visa_type = 'visa_free' and max_stay_days is not null
    then 'Sans visa pour les voyageurs marocains selon conditions. Séjour indicatif : ' || max_stay_days || ' jours.'
  when visa_type = 'visa_free'
    then 'Sans visa pour les voyageurs marocains selon conditions. Durée de séjour à vérifier avant le départ.'
  when visa_type in ('evisa', 'e_visa') and max_stay_days is not null
    then 'eVisa pour les voyageurs marocains selon conditions. Séjour indicatif : ' || max_stay_days || ' jours.'
  when visa_type in ('evisa', 'e_visa')
    then 'eVisa pour les voyageurs marocains selon conditions. Durée de séjour à vérifier avant le départ.'
  when visa_type in ('on_arrival', 'visa_on_arrival') and max_stay_days is not null
    then 'Visa à l’arrivée pour les voyageurs marocains selon conditions. Séjour indicatif : ' || max_stay_days || ' jours.'
  when visa_type in ('on_arrival', 'visa_on_arrival')
    then 'Visa à l’arrivée pour les voyageurs marocains selon conditions. Durée de séjour à vérifier avant le départ.'
  else notes
end
where notes is null
  or notes like '%?%'
  or notes like '%' || chr(195) || '%'
  or notes like '%' || chr(194) || '%'
  or notes like '%' || chr(226) || '%';

update destinations
set country = case country_code
  when 'DZ' then 'Algérie'
  when 'AM' then 'Arménie'
  when 'BA' then 'Bosnie-Herzégovine'
  when 'BJ' then 'Bénin'
  when 'BR' then 'Brésil'
  when 'EC' then 'Équateur'
  when 'CK' then 'Îles Cook'
  when 'MH' then 'Îles Marshall'
  when 'ET' then 'Éthiopie'
  when 'GE' then 'Géorgie'
  when 'GN' then 'Guinée'
  when 'HT' then 'Haïti'
  when 'ID' then 'Indonésie'
  when 'KR' then 'Corée du Sud'
  when 'CI' then 'Côte d’Ivoire'
  when 'CD' then 'République démocratique du Congo'
  when 'CG' then 'République du Congo'
  when 'DO' then 'République dominicaine'
  when 'ST' then 'São Tomé-et-Príncipe'
  when 'AE' then 'Émirats arabes unis'
  else country
end
where country_code in (
  'DZ',
  'AM',
  'BA',
  'BJ',
  'BR',
  'EC',
  'CK',
  'MH',
  'ET',
  'GE',
  'GN',
  'HT',
  'ID',
  'KR',
  'CI',
  'CD',
  'CG',
  'DO',
  'ST',
  'AE'
);

update destinations
set region = case
  when country_code in (
    'CK',
    'FJ',
    'FM',
    'KI',
    'MH',
    'NR',
    'NU',
    'PW',
    'SB',
    'TO',
    'TV',
    'VU',
    'WS'
  ) then 'Océanie'
  when country_code in (
    'AG',
    'BB',
    'BS',
    'CU',
    'DM',
    'DO',
    'GD',
    'HT',
    'JM',
    'KN',
    'LC',
    'TT',
    'VC'
  ) then 'Caraïbes'
  when country_code in (
    'AR',
    'BO',
    'BR',
    'CL',
    'CO',
    'EC',
    'GY',
    'PE',
    'PY',
    'SR',
    'UY',
    'VE'
  ) then 'Amérique du Sud'
  when country_code in (
    'CN',
    'HK',
    'JP',
    'KR',
    'MO',
    'MN',
    'TW'
  ) then 'Asie de l’Est'
  when country_code in (
    'BI',
    'DJ',
    'ER',
    'ET',
    'KE',
    'KM',
    'MG',
    'MU',
    'MW',
    'MZ',
    'RW',
    'SC',
    'SO',
    'TZ',
    'UG',
    'ZM',
    'ZW'
  ) then 'Afrique de l’Est'
  when country_code in (
    'BJ',
    'BF',
    'CI',
    'CV',
    'GH',
    'GM',
    'GN',
    'GW',
    'LR',
    'ML',
    'MR',
    'NE',
    'NG',
    'SN',
    'SL',
    'TG'
  ) then 'Afrique de l’Ouest'
  else region
end
where country_code in (
  'CK',
  'FJ',
  'FM',
  'KI',
  'MH',
  'NR',
  'NU',
  'PW',
  'SB',
  'TO',
  'TV',
  'VU',
  'WS',
  'AG',
  'BB',
  'BS',
  'CU',
  'DM',
  'DO',
  'GD',
  'HT',
  'JM',
  'KN',
  'LC',
  'TT',
  'VC',
  'AR',
  'BO',
  'BR',
  'CL',
  'CO',
  'EC',
  'GY',
  'PE',
  'PY',
  'SR',
  'UY',
  'VE',
  'CN',
  'HK',
  'JP',
  'KR',
  'MO',
  'MN',
  'TW',
  'BI',
  'DJ',
  'ER',
  'ET',
  'KE',
  'KM',
  'MG',
  'MU',
  'MW',
  'MZ',
  'RW',
  'SC',
  'SO',
  'TZ',
  'UG',
  'ZM',
  'ZW',
  'BJ',
  'BF',
  'CI',
  'CV',
  'GH',
  'GM',
  'GN',
  'GW',
  'LR',
  'ML',
  'MR',
  'NE',
  'NG',
  'SN',
  'SL',
  'TG'
);

update countries
set name = fixes.name
from (
  values
    ('AE', 'Émirats arabes unis'),
    ('AM', 'Arménie'),
    ('AZ', 'Azerbaïdjan'),
    ('BA', 'Bosnie-Herzégovine'),
    ('BE', 'Belgique'),
    ('BF', 'Burkina Faso'),
    ('BH', 'Bahreïn'),
    ('BJ', 'Bénin'),
    ('BN', 'Brunei'),
    ('BO', 'Bolivie'),
    ('BR', 'Brésil'),
    ('BY', 'Biélorussie'),
    ('CD', 'République démocratique du Congo'),
    ('CG', 'République du Congo'),
    ('CI', 'Côte d’Ivoire'),
    ('CK', 'Îles Cook'),
    ('CM', 'Cameroun'),
    ('CN', 'Chine'),
    ('CV', 'Cap-Vert'),
    ('DO', 'République dominicaine'),
    ('DZ', 'Algérie'),
    ('EC', 'Équateur'),
    ('EG', 'Égypte'),
    ('ER', 'Érythrée'),
    ('ES', 'Espagne'),
    ('FI', 'Finlande'),
    ('FJ', 'Fidji'),
    ('FM', 'Micronésie'),
    ('ET', 'Éthiopie'),
    ('GE', 'Géorgie'),
    ('GM', 'Gambie'),
    ('GN', 'Guinée'),
    ('GQ', 'Guinée équatoriale'),
    ('GR', 'Grèce'),
    ('GW', 'Guinée-Bissau'),
    ('HT', 'Haïti'),
    ('ID', 'Indonésie'),
    ('IE', 'Irlande'),
    ('IL', 'Israël'),
    ('JO', 'Jordanie'),
    ('JP', 'Japon'),
    ('KG', 'Kirghizistan'),
    ('KH', 'Cambodge'),
    ('KM', 'Comores'),
    ('KN', 'Saint-Christophe-et-Niévès'),
    ('KR', 'Corée du Sud'),
    ('LA', 'Laos'),
    ('LC', 'Sainte-Lucie'),
    ('LK', 'Sri Lanka'),
    ('LR', 'Libéria'),
    ('LS', 'Lesotho'),
    ('LT', 'Lituanie'),
    ('LU', 'Luxembourg'),
    ('LV', 'Lettonie'),
    ('ME', 'Monténégro'),
    ('MG', 'Madagascar'),
    ('MH', 'Îles Marshall'),
    ('MK', 'Macédoine du Nord'),
    ('ML', 'Mali'),
    ('MM', 'Birmanie'),
    ('MN', 'Mongolie'),
    ('MU', 'Maurice'),
    ('MZ', 'Mozambique'),
    ('NA', 'Namibie'),
    ('NE', 'Niger'),
    ('NG', 'Nigéria'),
    ('NP', 'Népal'),
    ('NZ', 'Nouvelle-Zélande'),
    ('PA', 'Panama'),
    ('PE', 'Pérou'),
    ('PG', 'Papouasie-Nouvelle-Guinée'),
    ('PH', 'Philippines'),
    ('PL', 'Pologne'),
    ('RO', 'Roumanie'),
    ('RS', 'Serbie'),
    ('RW', 'Rwanda'),
    ('SA', 'Arabie saoudite'),
    ('SC', 'Seychelles'),
    ('SG', 'Singapour'),
    ('SI', 'Slovénie'),
    ('SK', 'Slovaquie'),
    ('SN', 'Sénégal'),
    ('SO', 'Somalie'),
    ('ST', 'São Tomé-et-Príncipe'),
    ('SV', 'Salvador'),
    ('SY', 'Syrie'),
    ('TJ', 'Tadjikistan'),
    ('TH', 'Thaïlande'),
    ('TL', 'Timor oriental'),
    ('TM', 'Turkménistan'),
    ('TN', 'Tunisie'),
    ('TR', 'Turquie'),
    ('TW', 'Taïwan'),
    ('TZ', 'Tanzanie'),
    ('US', 'États-Unis'),
    ('UZ', 'Ouzbékistan'),
    ('VC', 'Saint-Vincent-et-les-Grenadines'),
    ('VN', 'Vietnam')
) as fixes(code, name)
where countries.code = fixes.code;

update destinations
set country = fixes.name
from (
  values
    ('AE', 'Émirats arabes unis'),
    ('AM', 'Arménie'),
    ('AZ', 'Azerbaïdjan'),
    ('BA', 'Bosnie-Herzégovine'),
    ('BE', 'Belgique'),
    ('BF', 'Burkina Faso'),
    ('BH', 'Bahreïn'),
    ('BJ', 'Bénin'),
    ('BN', 'Brunei'),
    ('BO', 'Bolivie'),
    ('BR', 'Brésil'),
    ('BY', 'Biélorussie'),
    ('CD', 'République démocratique du Congo'),
    ('CG', 'République du Congo'),
    ('CI', 'Côte d’Ivoire'),
    ('CK', 'Îles Cook'),
    ('CM', 'Cameroun'),
    ('CN', 'Chine'),
    ('CV', 'Cap-Vert'),
    ('DO', 'République dominicaine'),
    ('DZ', 'Algérie'),
    ('EC', 'Équateur'),
    ('EG', 'Égypte'),
    ('ER', 'Érythrée'),
    ('ES', 'Espagne'),
    ('FI', 'Finlande'),
    ('FJ', 'Fidji'),
    ('FM', 'Micronésie'),
    ('ET', 'Éthiopie'),
    ('GE', 'Géorgie'),
    ('GM', 'Gambie'),
    ('GN', 'Guinée'),
    ('GQ', 'Guinée équatoriale'),
    ('GR', 'Grèce'),
    ('GW', 'Guinée-Bissau'),
    ('HT', 'Haïti'),
    ('ID', 'Indonésie'),
    ('IE', 'Irlande'),
    ('IL', 'Israël'),
    ('JO', 'Jordanie'),
    ('JP', 'Japon'),
    ('KG', 'Kirghizistan'),
    ('KH', 'Cambodge'),
    ('KM', 'Comores'),
    ('KN', 'Saint-Christophe-et-Niévès'),
    ('KR', 'Corée du Sud'),
    ('LA', 'Laos'),
    ('LC', 'Sainte-Lucie'),
    ('LK', 'Sri Lanka'),
    ('LR', 'Libéria'),
    ('LS', 'Lesotho'),
    ('LT', 'Lituanie'),
    ('LU', 'Luxembourg'),
    ('LV', 'Lettonie'),
    ('ME', 'Monténégro'),
    ('MG', 'Madagascar'),
    ('MH', 'Îles Marshall'),
    ('MK', 'Macédoine du Nord'),
    ('ML', 'Mali'),
    ('MM', 'Birmanie'),
    ('MN', 'Mongolie'),
    ('MU', 'Maurice'),
    ('MZ', 'Mozambique'),
    ('NA', 'Namibie'),
    ('NE', 'Niger'),
    ('NG', 'Nigéria'),
    ('NP', 'Népal'),
    ('NZ', 'Nouvelle-Zélande'),
    ('PA', 'Panama'),
    ('PE', 'Pérou'),
    ('PG', 'Papouasie-Nouvelle-Guinée'),
    ('PH', 'Philippines'),
    ('PL', 'Pologne'),
    ('RO', 'Roumanie'),
    ('RS', 'Serbie'),
    ('RW', 'Rwanda'),
    ('SA', 'Arabie saoudite'),
    ('SC', 'Seychelles'),
    ('SG', 'Singapour'),
    ('SI', 'Slovénie'),
    ('SK', 'Slovaquie'),
    ('SN', 'Sénégal'),
    ('SO', 'Somalie'),
    ('ST', 'São Tomé-et-Príncipe'),
    ('SV', 'Salvador'),
    ('SY', 'Syrie'),
    ('TJ', 'Tadjikistan'),
    ('TH', 'Thaïlande'),
    ('TL', 'Timor oriental'),
    ('TM', 'Turkménistan'),
    ('TN', 'Tunisie'),
    ('TR', 'Turquie'),
    ('TW', 'Taïwan'),
    ('TZ', 'Tanzanie'),
    ('US', 'États-Unis'),
    ('UZ', 'Ouzbékistan'),
    ('VC', 'Saint-Vincent-et-les-Grenadines'),
    ('VN', 'Vietnam')
) as fixes(code, name)
where destinations.country_code = fixes.code;

update countries
set region = fixes.region
from (
  values
    ('CN', 'Asie de l’Est'),
    ('HK', 'Asie de l’Est'),
    ('JP', 'Asie de l’Est'),
    ('KR', 'Asie de l’Est'),
    ('MO', 'Asie de l’Est'),
    ('MN', 'Asie de l’Est'),
    ('TW', 'Asie de l’Est'),
    ('KH', 'Asie du Sud-Est'),
    ('ID', 'Asie du Sud-Est'),
    ('LA', 'Asie du Sud-Est'),
    ('MM', 'Asie du Sud-Est'),
    ('PH', 'Asie du Sud-Est'),
    ('SG', 'Asie du Sud-Est'),
    ('TH', 'Asie du Sud-Est'),
    ('TL', 'Asie du Sud-Est'),
    ('VN', 'Asie du Sud-Est'),
    ('BD', 'Asie du Sud'),
    ('BT', 'Asie du Sud'),
    ('IN', 'Asie du Sud'),
    ('LK', 'Asie du Sud'),
    ('MV', 'Asie du Sud'),
    ('NP', 'Asie du Sud'),
    ('PK', 'Asie du Sud'),
    ('CK', 'Océanie'),
    ('FJ', 'Océanie'),
    ('FM', 'Océanie'),
    ('KI', 'Océanie'),
    ('MH', 'Océanie'),
    ('NR', 'Océanie'),
    ('NU', 'Océanie'),
    ('NZ', 'Océanie'),
    ('PG', 'Océanie'),
    ('PW', 'Océanie'),
    ('SB', 'Océanie'),
    ('TO', 'Océanie'),
    ('TV', 'Océanie'),
    ('VU', 'Océanie'),
    ('WS', 'Océanie'),
    ('AG', 'Caraïbes'),
    ('BB', 'Caraïbes'),
    ('BS', 'Caraïbes'),
    ('CU', 'Caraïbes'),
    ('DM', 'Caraïbes'),
    ('DO', 'Caraïbes'),
    ('GD', 'Caraïbes'),
    ('HT', 'Caraïbes'),
    ('JM', 'Caraïbes'),
    ('KN', 'Caraïbes'),
    ('LC', 'Caraïbes'),
    ('TT', 'Caraïbes'),
    ('VC', 'Caraïbes'),
    ('AR', 'Amérique du Sud'),
    ('BO', 'Amérique du Sud'),
    ('BR', 'Amérique du Sud'),
    ('CL', 'Amérique du Sud'),
    ('CO', 'Amérique du Sud'),
    ('EC', 'Amérique du Sud'),
    ('GY', 'Amérique du Sud'),
    ('PE', 'Amérique du Sud'),
    ('PY', 'Amérique du Sud'),
    ('SR', 'Amérique du Sud'),
    ('UY', 'Amérique du Sud'),
    ('VE', 'Amérique du Sud'),
    ('BI', 'Afrique de l’Est'),
    ('DJ', 'Afrique de l’Est'),
    ('ER', 'Afrique de l’Est'),
    ('ET', 'Afrique de l’Est'),
    ('KE', 'Afrique de l’Est'),
    ('KM', 'Afrique de l’Est'),
    ('MG', 'Afrique de l’Est'),
    ('MU', 'Afrique de l’Est'),
    ('MW', 'Afrique de l’Est'),
    ('MZ', 'Afrique de l’Est'),
    ('RW', 'Afrique de l’Est'),
    ('SC', 'Afrique de l’Est'),
    ('SO', 'Afrique de l’Est'),
    ('TZ', 'Afrique de l’Est'),
    ('UG', 'Afrique de l’Est'),
    ('ZM', 'Afrique de l’Est'),
    ('ZW', 'Afrique de l’Est'),
    ('BJ', 'Afrique de l’Ouest'),
    ('BF', 'Afrique de l’Ouest'),
    ('CI', 'Afrique de l’Ouest'),
    ('CV', 'Afrique de l’Ouest'),
    ('GH', 'Afrique de l’Ouest'),
    ('GM', 'Afrique de l’Ouest'),
    ('GN', 'Afrique de l’Ouest'),
    ('GW', 'Afrique de l’Ouest'),
    ('LR', 'Afrique de l’Ouest'),
    ('ML', 'Afrique de l’Ouest'),
    ('MR', 'Afrique de l’Ouest'),
    ('NE', 'Afrique de l’Ouest'),
    ('NG', 'Afrique de l’Ouest'),
    ('SN', 'Afrique de l’Ouest'),
    ('SL', 'Afrique de l’Ouest'),
    ('TG', 'Afrique de l’Ouest')
) as fixes(code, region)
where countries.code = fixes.code;

update destinations
set region = fixes.region
from (
  values
    ('CN', 'Asie de l’Est'),
    ('HK', 'Asie de l’Est'),
    ('JP', 'Asie de l’Est'),
    ('KR', 'Asie de l’Est'),
    ('MO', 'Asie de l’Est'),
    ('MN', 'Asie de l’Est'),
    ('TW', 'Asie de l’Est'),
    ('KH', 'Asie du Sud-Est'),
    ('ID', 'Asie du Sud-Est'),
    ('LA', 'Asie du Sud-Est'),
    ('MM', 'Asie du Sud-Est'),
    ('PH', 'Asie du Sud-Est'),
    ('SG', 'Asie du Sud-Est'),
    ('TH', 'Asie du Sud-Est'),
    ('TL', 'Asie du Sud-Est'),
    ('VN', 'Asie du Sud-Est'),
    ('BD', 'Asie du Sud'),
    ('BT', 'Asie du Sud'),
    ('IN', 'Asie du Sud'),
    ('LK', 'Asie du Sud'),
    ('MV', 'Asie du Sud'),
    ('NP', 'Asie du Sud'),
    ('PK', 'Asie du Sud'),
    ('CK', 'Océanie'),
    ('FJ', 'Océanie'),
    ('FM', 'Océanie'),
    ('KI', 'Océanie'),
    ('MH', 'Océanie'),
    ('NR', 'Océanie'),
    ('NU', 'Océanie'),
    ('NZ', 'Océanie'),
    ('PG', 'Océanie'),
    ('PW', 'Océanie'),
    ('SB', 'Océanie'),
    ('TO', 'Océanie'),
    ('TV', 'Océanie'),
    ('VU', 'Océanie'),
    ('WS', 'Océanie'),
    ('AG', 'Caraïbes'),
    ('BB', 'Caraïbes'),
    ('BS', 'Caraïbes'),
    ('CU', 'Caraïbes'),
    ('DM', 'Caraïbes'),
    ('DO', 'Caraïbes'),
    ('GD', 'Caraïbes'),
    ('HT', 'Caraïbes'),
    ('JM', 'Caraïbes'),
    ('KN', 'Caraïbes'),
    ('LC', 'Caraïbes'),
    ('TT', 'Caraïbes'),
    ('VC', 'Caraïbes'),
    ('AR', 'Amérique du Sud'),
    ('BO', 'Amérique du Sud'),
    ('BR', 'Amérique du Sud'),
    ('CL', 'Amérique du Sud'),
    ('CO', 'Amérique du Sud'),
    ('EC', 'Amérique du Sud'),
    ('GY', 'Amérique du Sud'),
    ('PE', 'Amérique du Sud'),
    ('PY', 'Amérique du Sud'),
    ('SR', 'Amérique du Sud'),
    ('UY', 'Amérique du Sud'),
    ('VE', 'Amérique du Sud'),
    ('BI', 'Afrique de l’Est'),
    ('DJ', 'Afrique de l’Est'),
    ('ER', 'Afrique de l’Est'),
    ('ET', 'Afrique de l’Est'),
    ('KE', 'Afrique de l’Est'),
    ('KM', 'Afrique de l’Est'),
    ('MG', 'Afrique de l’Est'),
    ('MU', 'Afrique de l’Est'),
    ('MW', 'Afrique de l’Est'),
    ('MZ', 'Afrique de l’Est'),
    ('RW', 'Afrique de l’Est'),
    ('SC', 'Afrique de l’Est'),
    ('SO', 'Afrique de l’Est'),
    ('TZ', 'Afrique de l’Est'),
    ('UG', 'Afrique de l’Est'),
    ('ZM', 'Afrique de l’Est'),
    ('ZW', 'Afrique de l’Est'),
    ('BJ', 'Afrique de l’Ouest'),
    ('BF', 'Afrique de l’Ouest'),
    ('CI', 'Afrique de l’Ouest'),
    ('CV', 'Afrique de l’Ouest'),
    ('GH', 'Afrique de l’Ouest'),
    ('GM', 'Afrique de l’Ouest'),
    ('GN', 'Afrique de l’Ouest'),
    ('GW', 'Afrique de l’Ouest'),
    ('LR', 'Afrique de l’Ouest'),
    ('ML', 'Afrique de l’Ouest'),
    ('MR', 'Afrique de l’Ouest'),
    ('NE', 'Afrique de l’Ouest'),
    ('NG', 'Afrique de l’Ouest'),
    ('SN', 'Afrique de l’Ouest'),
    ('SL', 'Afrique de l’Ouest'),
    ('TG', 'Afrique de l’Ouest')
) as fixes(code, region)
where destinations.country_code = fixes.code;
